apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpaas-ui
  namespace: kpaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpaas-ui
  template:
    metadata:
      labels:
        app: kpaas-ui
    spec:
      containers:
      - image: imyujinsim/edu-msa-ui:30 
        name: kpaas-ui
