apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpaas-ui
  namespace: kpaas
  labels:
    app: kpaas-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpaas-ui
  template:
    metadata:
      labels:
        app: kpaas-ui
    spec:
      containers:
      - name: kpaas-ui
        image: docker.io/imyujinsim/edu-msa-ui:43
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metedata :
  name: kpaas-ui
  namespace: kpaas
  labels:
    app: kpaas-ui
spec:
  selector:
    app: kpaas-ui
  type: NodePort
  port: 9090
  targetPort: 5000
