apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpaas-ui
  namespace: kpaas
  labels:
    app: kpaas-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpaas-ui
  template:
    metadata:
      labels:
        app: kpaas-ui
    spec:
      containers:
      - name: kpaas-ui
        image: docker.io/imyujinsim/edu-msa-ui:43
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: kpaas-ui
  namespace: kpaas
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kpaas-ui
  ports:
      # 기본적으로 그리고 편의상 `targetPort` 는 `port` 필드와 동일한 값으로 설정된다.
    - port: 9000
      targetPort: 9000
      nodePort: 9000
